services:
  app:
    build: .
    container_name: adapt_ed_backend
    restart: unless-stopped
    env_file:
      - ./infra/.env
      - .env
    ports:
      - "${SR_AP_PORT:-8000}:8000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - adapt_ed_net

networks:
  adapt_ed_net:
    external: true
