services:
  app:
    build: .
    container_name: adapt_ed_backend
    restart: unless-stopped
    env_file:
      - ./infra/.env
    environment:
      # Внутри Docker-сети хосты и порты другие
      PG_HOST: postgres
      PG_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MINIO_HOST: minio
      APP_HOST: 0.0.0.0
    ports:
      - "${APP_PORT:-8000}:8000"
    networks:
      - adapt_ed_net

networks:
  adapt_ed_net:
    external: true
