// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Выполняет вход по email и паролю, возвращает пару токенов.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Аутентификация",
                "parameters": [
                    {
                        "description": "Учётные данные",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Неверный email или пароль",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Инвалидирует переданный refresh token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Выход из текущей сессии",
                "parameters": [
                    {
                        "description": "Refresh token текущей сессии",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.LogoutRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.LogoutResponse"
                        }
                    },
                    "401": {
                        "description": "Не авторизован",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/logout-all": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Инвалидирует все refresh token текущего пользователя и увеличивает версию сессии.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Выход со всех устройств",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.LogoutResponse"
                        }
                    },
                    "401": {
                        "description": "Не авторизован",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает данные авторизованного пользователя по JWT.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Текущий пользователь",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.GetMeResponse"
                        }
                    },
                    "401": {
                        "description": "Не авторизован",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "description": "Принимает refresh token и user_id, возвращает новую пару access + refresh.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Обновление токенов",
                "parameters": [
                    {
                        "description": "Refresh token и ID пользователя",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.RefreshRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.RefreshResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Невалидный или истёкший refresh token",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/registration": {
            "post": {
                "description": "Создаёт нового пользователя с ролью student и возвращает пару токенов.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Самостоятельная регистрация",
                "parameters": [
                    {
                        "description": "Данные регистрации",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.RegistrationRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/auth.RegistrationResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Email уже зарегистрирован",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/registration/admin": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Создаёт пользователя с указанной ролью и генерирует временный пароль. Для school_admin school_id подставляется автоматически из токена.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Создание пользователя админом",
                "parameters": [
                    {
                        "description": "Данные нового пользователя",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.RegistrationRequestByAdmin"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/auth.RegistrationResponseByAdmin"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Недостаточно прав",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Email уже зарегистрирован",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/infra/health": {
            "get": {
                "description": "Возвращает успешный ответ, если HTTP-сервис запущен и способен обрабатывать запросы.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "infra"
                ],
                "summary": "Проверка доступности сервиса",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.HealthResponse"
                        }
                    }
                }
            }
        },
        "/infra/metrics": {
            "get": {
                "description": "Возвращает метрики приложения в формате Prometheus для внешнего сбора и мониторинга.",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "infra"
                ],
                "summary": "Метрики приложения",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/infra/ready": {
            "get": {
                "description": "Проверяет готовность приложения к обработке трафика и доступность критичных зависимостей, таких как база данных и кэш.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "infra"
                ],
                "summary": "Проверка готовности сервиса",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.ReadyResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/schools": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает список школ с фильтрацией и пагинацией.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schools"
                ],
                "summary": "Список школ",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Поиск по названию (подстрока)",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Фильтр по городу",
                        "name": "city",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Количество записей (по умолчанию 20, макс 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Смещение (по умолчанию 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/school.ListResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Создаёт новую школу. Доступно только super_admin.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schools"
                ],
                "summary": "Создание школы",
                "parameters": [
                    {
                        "description": "Данные школы",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/school.CreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/school.SchoolResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Недостаточно прав",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/schools/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает данные школы по ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schools"
                ],
                "summary": "Получение школы",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID школы",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/school.SchoolResponse"
                        }
                    },
                    "404": {
                        "description": "Школа не найдена",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Мягкое удаление школы. Доступно только super_admin.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schools"
                ],
                "summary": "Удаление школы",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID школы",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/school.SchoolID"
                        }
                    },
                    "403": {
                        "description": "Недостаточно прав",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Школа не найдена",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Обновляет данные школы. Доступно super_admin и school_admin своей школы.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schools"
                ],
                "summary": "Обновление школы",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID школы",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Обновляемые поля",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/school.UpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/school.SchoolResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Недостаточно прав",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Школа не найдена",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.GetMeResponse": {
            "type": "object",
            "required": [
                "email",
                "first_name",
                "last_name",
                "role"
            ],
            "properties": {
                "avatar_key": {
                    "type": "string",
                    "example": "avatars/10cb44c1/photo.png"
                },
                "class_id": {
                    "type": "string",
                    "example": "1db34ac1-23f1-4b47-82e3-9e8ad16ee1fb"
                },
                "created_at": {
                    "type": "string",
                    "example": "2026-03-16T10:30:00Z"
                },
                "email": {
                    "type": "string",
                    "example": "example@example.com"
                },
                "first_name": {
                    "type": "string",
                    "example": "Иван"
                },
                "id": {
                    "type": "string",
                    "example": "10cb44c1-18f7-4a3e-b0bd-5d2609619d65"
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "last_name": {
                    "type": "string",
                    "example": "Иванов"
                },
                "middle_name": {
                    "type": "string",
                    "example": "Иванович"
                },
                "role": {
                    "enum": [
                        "student",
                        "teacher",
                        "school_admin",
                        "super_admin"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/dto.UserRole"
                        }
                    ],
                    "example": "student"
                },
                "school_id": {
                    "type": "string",
                    "example": "3e1b8139-1f9d-458f-ac70-41f815c8b128"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2026-03-16T10:30:00Z"
                }
            }
        },
        "auth.LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "example@example.com"
                },
                "password": {
                    "type": "string",
                    "minLength": 8,
                    "example": "NFMpC9!fm;ARqoh"
                }
            }
        },
        "auth.LoginResponse": {
            "type": "object",
            "required": [
                "email",
                "first_name",
                "last_name",
                "role"
            ],
            "properties": {
                "access_token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                },
                "class_id": {
                    "type": "string",
                    "example": "1db34ac1-23f1-4b47-82e3-9e8ad16ee1fb"
                },
                "created_at": {
                    "type": "string",
                    "example": "2026-03-16T10:30:00Z"
                },
                "email": {
                    "type": "string",
                    "example": "example@example.com"
                },
                "first_name": {
                    "type": "string",
                    "example": "Иван"
                },
                "id": {
                    "type": "string",
                    "example": "10cb44c1-18f7-4a3e-b0bd-5d2609619d65"
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "last_name": {
                    "type": "string",
                    "example": "Иванов"
                },
                "middle_name": {
                    "type": "string",
                    "example": "Иванович"
                },
                "refresh_token": {
                    "type": "string",
                    "example": "b7d0e8d1-47d8-4d3e-8c2b-7b1d0e8a1234"
                },
                "role": {
                    "enum": [
                        "student",
                        "teacher",
                        "school_admin",
                        "super_admin"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/dto.UserRole"
                        }
                    ],
                    "example": "student"
                },
                "school_id": {
                    "type": "string",
                    "example": "3e1b8139-1f9d-458f-ac70-41f815c8b128"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2026-03-16T10:30:00Z"
                }
            }
        },
        "auth.LogoutRequest": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "type": "string",
                    "example": "b7d0e8d1-47d8-4d3e-8c2b-7b1d0e8a1234"
                }
            }
        },
        "auth.LogoutResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "10cb44c1-18f7-4a3e-b0bd-5d2609619d65"
                }
            }
        },
        "auth.RefreshRequest": {
            "type": "object",
            "required": [
                "refresh_token",
                "user_id"
            ],
            "properties": {
                "refresh_token": {
                    "type": "string",
                    "example": "b7d0e8d1-47d8-4d3e-8c2b-7b1d0e8a1234"
                },
                "user_id": {
                    "type": "string",
                    "example": "10cb44c1-18f7-4a3e-b0bd-5d2609619d65"
                }
            }
        },
        "auth.RefreshResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                },
                "refresh_token": {
                    "type": "string",
                    "example": "b7d0e8d1-47d8-4d3e-8c2b-7b1d0e8a1234"
                }
            }
        },
        "auth.RegistrationRequest": {
            "type": "object",
            "required": [
                "email",
                "first_name",
                "last_name",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "example@example.com"
                },
                "first_name": {
                    "type": "string",
                    "example": "Иван"
                },
                "last_name": {
                    "type": "string",
                    "example": "Иванов"
                },
                "middle_name": {
                    "type": "string",
                    "example": "Иванович"
                },
                "password": {
                    "type": "string",
                    "minLength": 8,
                    "example": "NFMpC9!fm;ARqoh"
                }
            }
        },
        "auth.RegistrationRequestByAdmin": {
            "type": "object",
            "required": [
                "email",
                "first_name",
                "last_name",
                "role"
            ],
            "properties": {
                "class_id": {
                    "type": "string",
                    "example": "1db34ac1-23f1-4b47-82e3-9e8ad16ee1fb"
                },
                "email": {
                    "type": "string",
                    "example": "example@example.com"
                },
                "first_name": {
                    "type": "string",
                    "example": "Иван"
                },
                "last_name": {
                    "type": "string",
                    "example": "Иванов"
                },
                "middle_name": {
                    "type": "string",
                    "example": "Иванович"
                },
                "role": {
                    "enum": [
                        "student",
                        "teacher",
                        "school_admin",
                        "super_admin"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/dto.UserRole"
                        }
                    ],
                    "example": "student"
                },
                "school_id": {
                    "type": "string",
                    "example": "3e1b8139-1f9d-458f-ac70-41f815c8b128"
                }
            }
        },
        "auth.RegistrationResponse": {
            "type": "object",
            "required": [
                "email",
                "first_name",
                "last_name",
                "role"
            ],
            "properties": {
                "access_token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                },
                "class_id": {
                    "type": "string",
                    "example": "1db34ac1-23f1-4b47-82e3-9e8ad16ee1fb"
                },
                "created_at": {
                    "type": "string",
                    "example": "2026-03-16T10:30:00Z"
                },
                "email": {
                    "type": "string",
                    "example": "example@example.com"
                },
                "first_name": {
                    "type": "string",
                    "example": "Иван"
                },
                "id": {
                    "type": "string",
                    "example": "10cb44c1-18f7-4a3e-b0bd-5d2609619d65"
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "last_name": {
                    "type": "string",
                    "example": "Иванов"
                },
                "middle_name": {
                    "type": "string",
                    "example": "Иванович"
                },
                "refresh_token": {
                    "type": "string",
                    "example": "b7d0e8d1-47d8-4d3e-8c2b-7b1d0e8a1234"
                },
                "role": {
                    "enum": [
                        "student",
                        "teacher",
                        "school_admin",
                        "super_admin"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/dto.UserRole"
                        }
                    ],
                    "example": "student"
                },
                "school_id": {
                    "type": "string",
                    "example": "3e1b8139-1f9d-458f-ac70-41f815c8b128"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2026-03-16T10:30:00Z"
                }
            }
        },
        "auth.RegistrationResponseByAdmin": {
            "type": "object",
            "required": [
                "email",
                "first_name",
                "last_name",
                "role"
            ],
            "properties": {
                "class_id": {
                    "type": "string",
                    "example": "1db34ac1-23f1-4b47-82e3-9e8ad16ee1fb"
                },
                "created_at": {
                    "type": "string",
                    "example": "2026-03-16T10:30:00Z"
                },
                "email": {
                    "type": "string",
                    "example": "example@example.com"
                },
                "first_name": {
                    "type": "string",
                    "example": "Иван"
                },
                "id": {
                    "type": "string",
                    "example": "10cb44c1-18f7-4a3e-b0bd-5d2609619d65"
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "last_name": {
                    "type": "string",
                    "example": "Иванов"
                },
                "middle_name": {
                    "type": "string",
                    "example": "Иванович"
                },
                "password": {
                    "type": "string",
                    "example": "NFMpC9!fm;ARqoh"
                },
                "role": {
                    "enum": [
                        "student",
                        "teacher",
                        "school_admin",
                        "super_admin"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/dto.UserRole"
                        }
                    ],
                    "example": "student"
                },
                "school_id": {
                    "type": "string",
                    "example": "3e1b8139-1f9d-458f-ac70-41f815c8b128"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2026-03-16T10:30:00Z"
                }
            }
        },
        "dto.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "VALIDATION_ERROR"
                },
                "message": {
                    "type": "string",
                    "example": "Некорректный формат email"
                },
                "request_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "dto.UserRole": {
            "type": "string",
            "enum": [
                "student",
                "teacher",
                "school_admin",
                "super_admin"
            ],
            "x-enum-varnames": [
                "RoleStudent",
                "RoleTeacher",
                "RoleSchoolAdmin",
                "RoleSuperAdmin"
            ]
        },
        "handlers.HealthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "handlers.ReadyResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ready"
                }
            }
        },
        "school.CreateRequest": {
            "type": "object",
            "required": [
                "city",
                "name"
            ],
            "properties": {
                "city": {
                    "description": "Город школы",
                    "type": "string",
                    "example": "Воронеж"
                },
                "name": {
                    "description": "Наименование школы",
                    "type": "string",
                    "example": "МКОУ 'Никольская СОШ'"
                }
            }
        },
        "school.ListResponse": {
            "type": "object",
            "properties": {
                "schools": {
                    "description": "Список школ",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/school.SchoolResponse"
                    }
                },
                "total": {
                    "description": "Общее количество записей",
                    "type": "integer",
                    "example": 42
                }
            }
        },
        "school.SchoolID": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "UUID школы",
                    "type": "string",
                    "example": "10cb44c1-18f7-4a3e-b0bd-5d2609619d65"
                }
            }
        },
        "school.SchoolResponse": {
            "type": "object",
            "required": [
                "city",
                "name"
            ],
            "properties": {
                "city": {
                    "description": "Город школы",
                    "type": "string",
                    "example": "Воронеж"
                },
                "created_at": {
                    "description": "Дата создания школы",
                    "type": "string",
                    "example": "2026-03-16T10:30:00Z"
                },
                "id": {
                    "description": "UUID школы",
                    "type": "string",
                    "example": "10cb44c1-18f7-4a3e-b0bd-5d2609619d65"
                },
                "logo_key": {
                    "description": "Ключ логотипа в S3-хранилище",
                    "type": "string",
                    "example": "logos/10cb44c1/photo.png"
                },
                "name": {
                    "description": "Наименование школы",
                    "type": "string",
                    "example": "МКОУ 'Никольская СОШ'"
                },
                "updated_at": {
                    "description": "Дата последнего обновления школы",
                    "type": "string",
                    "example": "2026-03-16T10:30:00Z"
                }
            }
        },
        "school.UpdateRequest": {
            "type": "object",
            "properties": {
                "city": {
                    "description": "Город школы",
                    "type": "string",
                    "example": "Воронеж"
                },
                "logo_key": {
                    "description": "Ключ логотипа в S3-хранилище",
                    "type": "string",
                    "example": "logos/10cb44c1/photo.png"
                },
                "name": {
                    "description": "Наименование школы",
                    "type": "string",
                    "example": "МКОУ 'Никольская СОШ'"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Введите токен в формате: Bearer {access_token}",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "tags": [
        {
            "description": "Служебные эндпоинты приложения: доступность, готовность и метрики мониторинга.",
            "name": "infra"
        },
        {
            "description": "Эндпоинты для работы с авторизацией пользователей",
            "name": "auth"
        },
        {
            "description": "Управление школами: создание, обновление, удаление и поиск.",
            "name": "schools"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "API",
	Description:      "API description",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
